// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asp.net_core_store.Models;

namespace asp.net_core_store.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20200225222822_initCreate")]
    partial class initCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("asp.net_core_store.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 90m,
                            ItemName = "Product1",
                            Price = 100m,
                            Status = false
                        },
                        new
                        {
                            Id = 2,
                            Cost = 100m,
                            ItemName = "Product2",
                            Price = 120m,
                            Status = false
                        },
                        new
                        {
                            Id = 3,
                            Cost = 150m,
                            ItemName = "Product3",
                            Price = 200m,
                            Status = false
                        },
                        new
                        {
                            Id = 4,
                            Cost = 120m,
                            ItemName = "Product4",
                            Price = 150m,
                            Status = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
